#!/usr/bin/env bun
import { homedir } from "os"
import { join } from "path"
import { createApiClient } from "./packages/core/api-client/src/client"

// Read the per-install sidecar password generated by the Tauri host on first
// launch. ULTRAWORK_SIDECAR_PASSWORD env can override.
async function loadCreds(): Promise<{ username: string; password: string }> {
  const envPw = process.env.ULTRAWORK_SIDECAR_PASSWORD
  if (envPw) {
    return {
      username: process.env.ULTRAWORK_SIDECAR_USERNAME || "opencode",
      password: envPw,
    }
  }
  const credsPath = join(homedir(), ".config", "ultrawork", "sidecar-auth.json")
  const file = Bun.file(credsPath)
  if (!(await file.exists())) {
    console.error(`❌ Sidecar credentials not found at ${credsPath}`)
    console.error("   Run the Ultrawork app at least once, or set ULTRAWORK_SIDECAR_PASSWORD.")
    process.exit(1)
  }
  return await file.json()
}

async function test() {
  const creds = await loadCreds()
  const client = createApiClient({
    baseUrl: "http://127.0.0.1:4096",
    username: creds.username,
    password: creds.password,
  })

  try {
    console.log("Creating session...")
    const session = await client.createSession({
      workingDirectory: process.cwd(),
    })
    console.log("✅ Session created:", session.id)

    console.log("\nSending message...")
    await client.promptAsync(session.id, "Hello, OpenCode!")
    console.log("✅ Message sent")

    console.log("\nTest completed successfully!")
  } catch (error) {
    console.error("❌ Test failed:", error)
    process.exit(1)
  }
}

test()
