#!/usr/bin/env python3
"""deckcraft QA gate — validate page fragments against the spec_lock contract.

    python3 validate_deck.py <project_dir> [--single]

  --single   first-page-gate mode: skip deck-level checks (E7 diversity,
             page-count vs outline) so a lone probe page can be validated
             before fanning out the rest.

Style rules are checked against style="..." attribute contents only — visible
text is free to mention "Gradient Descent", HTML entities (&#8212;), issue
numbers (#123) etc. without tripping the gate.

Checks (ERROR fails the gate, WARN is advisory):
  E1 literal colors in style attributes or SVG presentation attributes —
     hex/rgb/hsl AND CSS named colors (white/crimson/…); palette vars only
  E2 literal font-size in any unit (px/pt/em/rem/vw/…) — ramp vars only
  E3 var() reference not defined in tokens.css
  E4 forbidden styling: gradient (incl. SVG <linearGradient>/<radialGradient>),
     box-shadow, italic, underline decoration; <script>/<style> tags
  E5 data-layout/data-rhythm missing, unknown (registry = layouts.html), or
     mismatching outline.json; page numbers not contiguous 1..N or != outline
  E6 placeholder residue / generator signatures in visible text
  E7 layout diversity: >=8 pages need >=6 distinct; 3+ consecutive same layout
  E8 fragment shape: not exactly one <section> (open AND close), "slide" class
  E9 hidden content (display:none/visibility:hidden/opacity:0) — nothing on a
     static 1280x720 slide may be invisible (also defeats hiding gate-dodges)
  E10 scenario pages (per outline evidence) must carry a VISIBLE 「示意」 label
  W1 style margin/padding/gap not on the 8px module (border widths exempt)
  W2 breathing page unusually text-heavy (> 120 visible chars)

Exit 0 = pass (warnings allowed), 1 = errors found, 2 = usage/setup problem.
"""
from __future__ import annotations

import itertools
import json
import re
import sys
from pathlib import Path

from console_encoding import configure_utf8_stdio

configure_utf8_stdio()

SKILL_DIR = Path(__file__).resolve().parent.parent
VALID_RHYTHMS = {"anchor", "dense", "breathing"}
# Placeholder scan runs on visible text: word-boundary + uppercase TODO so
# "Todoist"/"todos" don't trip it; lorem/ipsum stay case-insensitive.
PLACEHOLDER_RES = [
    re.compile(r"\blorem\b|\bipsum\b", re.I),
    re.compile(r"\bTODO\b(?!-)"),  # (?!-) exempts compounds like "TODO-list 工具"
    re.compile(r"待补充|\[insert|占位符"),
    # generator watermark/signature — narrow to explicit tool attribution so
    # legit prose ("revenue generated by Q3", "自动生成代码") doesn't trip it
    re.compile(r"(?:generated|made|created)\s+(?:by|with)\s+"
               r"(?:deckcraft|ai|gpt|claude|chatgpt)\b"
               r"|由\s*(?:AI|GPT|Claude|大模型|deckcraft)\s*生成", re.I),
]
# Style-attribute-scoped forbidden rules (E4).
FORBIDDEN_STYLE = [
    (re.compile(r"gradient", re.I), "gradient"),
    (re.compile(r"box-shadow"), "box-shadow"),
    (re.compile(r"font-style:\s*italic"), "italic (CJK 禁假斜体)"),
    (re.compile(r"text-decoration:\s*underline"), "underline decoration"),
]
FORBIDDEN_TAGS = [
    (re.compile(r"<script", re.I), "script tag"),
    (re.compile(r"<style", re.I), "style tag (tokens live in tokens.css only)"),
    (re.compile(r"<(?:linear|radial)Gradient\b", re.I), "SVG gradient element"),
]
HIDDEN_STYLE = re.compile(r"display\s*:\s*none|visibility\s*:\s*hidden|opacity\s*:\s*0(?![.\d])")
# CSS named colors (full keyword list) — a literal color is a literal color
# whether it's spelled #dc143c or crimson; only var(--c-*) may color anything.
NAMED_COLORS = frozenset("""
aliceblue antiquewhite aqua aquamarine azure beige bisque black blanchedalmond
blue blueviolet brown burlywood cadetblue chartreuse chocolate coral
cornflowerblue cornsilk crimson cyan darkblue darkcyan darkgoldenrod darkgray
darkgreen darkgrey darkkhaki darkmagenta darkolivegreen darkorange darkorchid
darkred darksalmon darkseagreen darkslateblue darkslategray darkslategrey
darkturquoise darkviolet deeppink deepskyblue dimgray dimgrey dodgerblue
firebrick floralwhite forestgreen fuchsia gainsboro ghostwhite gold goldenrod
gray green greenyellow grey honeydew hotpink indianred indigo ivory khaki
lavender lavenderblush lawngreen lemonchiffon lightblue lightcoral lightcyan
lightgoldenrodyellow lightgray lightgreen lightgrey lightpink lightsalmon
lightseagreen lightskyblue lightslategray lightslategrey lightsteelblue
lightyellow lime limegreen linen magenta maroon mediumaquamarine mediumblue
mediumorchid mediumpurple mediumseagreen mediumslateblue mediumspringgreen
mediumturquoise mediumvioletred midnightblue mintcream mistyrose moccasin
navajowhite navy oldlace olive olivedrab orange orangered orchid palegoldenrod
palegreen paleturquoise palevioletred papayawhip peachpuff peru pink plum
powderblue purple rebeccapurple red rosybrown royalblue saddlebrown salmon
sandybrown seagreen seashell sienna silver skyblue slateblue slategray
slategrey snow springgreen steelblue tan teal thistle tomato turquoise violet
wheat white whitesmoke yellow yellowgreen
""".split())
# style properties that can carry a color value
COLOR_PROPS = re.compile(
    r"color|background|border|outline|fill|stroke|shadow|caret|column-rule|text-emphasis")
# SVG presentation attributes that colorize without style="...". Lookbehind
# (?<![\w-]) instead of \b so data-fill="…" / x-stroke="…" don't match the
# fill/stroke tail of a hyphenated custom attribute name.
SVG_COLOR_ATTR = re.compile(r"""(?<![\w-])(fill|stroke|stop-color|flood-color|lighting-color)\s*=\s*["']([^"']*)["']""")
SVG_ATTR_ALLOWED = {"none", "currentcolor", "transparent", "inherit"}
# E10 scenario-label markers by outline language — a scenario page must carry a
# VISIBLE "this is illustrative" label; the schema allows language:"en" decks, so
# an English deck labels in English rather than being forced to embed 示意/虚构.
SCENARIO_LABELS = {
    "zh": ("示意", "虚构"), "zh-hans": ("示意", "虚构"), "zh-hant": ("示意", "虛構"),
    "en": ("illustrative", "sample", "scenario", "not real", "for illustration"),
}
SCENARIO_LABELS_ANY = tuple(m for ms in SCENARIO_LABELS.values() for m in ms)


def named_color_hits(style_text: str) -> list[str]:
    """Named-color literals inside color-capable declarations of style attrs.

    var(--c-gold) and url(images/navy-bg.png) are stripped first: a color word
    inside a token name (validated separately by E3) or an image filename is not
    a literal color and must not trip the gate."""
    hits = []
    for decl in style_text.split(";"):
        prop, _, value = decl.partition(":")
        if not value or not COLOR_PROPS.search(prop.strip().lower()):
            continue
        clean = re.sub(r"var\([^)]*\)|url\([^)]*\)", " ", value.lower())
        for tok in re.findall(r"[a-zA-Z]+", clean):
            if tok in NAMED_COLORS:
                hits.append(f"{prop.strip()}: {tok}")
    return hits


def valid_layouts() -> set[str]:
    """Layout registry SSOT is layouts.html — parse it so adding S11 there
    can never desync this hard gate. Fallback: S01–S10."""
    reg = SKILL_DIR / "assets" / "templates" / "layouts.html"
    if reg.is_file():
        found = set(re.findall(r'data-layout="(S\d{2})"', reg.read_text(encoding="utf-8")))
        if found:
            return found
    return {f"S{i:02d}" for i in range(1, 11)}


def page_no(p: Path) -> int:
    m = re.search(r"(\d+)", p.stem)
    return int(m.group(1)) if m else 0


def main() -> int:
    args = [x for x in sys.argv[1:] if x != "--single"]
    single = "--single" in sys.argv[1:]
    if len(args) != 1:
        print(__doc__, file=sys.stderr)
        return 2
    proj = Path(args[0])
    pages = sorted((proj / "pages").glob("page-*.html"), key=page_no)
    tokens_f = proj / "tokens.css"
    if not pages or not tokens_f.is_file():
        print(f"ERROR: need {proj}/pages/page-*.html and tokens.css", file=sys.stderr)
        return 2

    allowed_vars = set(re.findall(r"(--[\w-]+)\s*:", tokens_f.read_text(encoding="utf-8")))
    layouts_registry = valid_layouts()
    outline = {}
    outline_f = proj / "outline.json"
    lang = "zh"
    if outline_f.is_file():
        try:
            data = json.loads(outline_f.read_text(encoding="utf-8"))
            outline = {s["index"]: s for s in data.get("slides", []) if "index" in s}
            lang = str(data.get("language") or "zh").lower()
        except (json.JSONDecodeError, KeyError, TypeError):
            print("WARN: outline.json unreadable — skipping cross-checks")
    # accept the language's own markers; fall back to any known marker so a
    # bilingual label ("示意 / illustrative") always satisfies E10
    scenario_markers = SCENARIO_LABELS.get(lang) or SCENARIO_LABELS_ANY

    errors: list[str] = []
    warns: list[str] = []
    layouts: list[str] = []

    for p in pages:
        n = page_no(p)
        t = p.read_text(encoding="utf-8")
        body = re.sub(r"<!--.*?-->", "", t, flags=re.S)
        # Match single- OR double-quoted style attrs, with optional spaces around
        # `=` — Chrome renders `style='…'` and `style = "…"` identically, so a
        # double-quote-only regex would let literal colors / font-sizes / gradients /
        # opacity:0 hides silently escape E1/E2/E4/E9 (a real gate-dodge).
        style_text = " ".join(re.findall(r'style\s*=\s*["\']([^"\']*)["\']', body))
        visible = re.sub(r"<[^>]+>", " ", body)

        # E8 fragment shape — export splitting and shell styling both rely on it.
        # Close tags counted too: a stray </section> would make split_pages
        # silently truncate the page tail in every derivative.
        n_open = len(re.findall(r"<section\b", body))
        n_close = len(re.findall(r"</section>", body))
        if n_open != 1 or n_close != 1:
            errors.append(f"E8 {p.name}: expected exactly one <section>…</section>, "
                          f"found {n_open} open / {n_close} close")
        sec_tag = re.search(r"<section\b[^>]*>", body)
        if sec_tag and not re.search(r'class="[^"]*\bslide\b[^"]*"', sec_tag.group(0)):
            errors.append(f"E8 {p.name}: <section> missing the \"slide\" class")

        for m in re.findall(r"#[0-9a-fA-F]{3,8}\b|rgba?\(|hsla?\(", style_text):
            errors.append(f"E1 {p.name}: literal color {m}")
        for hit in named_color_hits(style_text):
            errors.append(f"E1 {p.name}: literal named color ({hit})")
        for attr, val in SVG_COLOR_ATTR.findall(body):
            if val.strip().lower() not in SVG_ATTR_ALLOWED:
                errors.append(f"E1 {p.name}: literal color in SVG attribute {attr}=\"{val}\" "
                              f"(use currentColor and color the parent via var)")
        for m in re.findall(r"font-size:\s*([\d.]+(?:px|pt|em|rem|vw|vh|vmin|vmax|ch|ex|%))",
                            style_text):
            errors.append(f"E2 {p.name}: literal font-size {m}")
        if HIDDEN_STYLE.search(style_text):
            errors.append(f"E9 {p.name}: hidden content (display:none/visibility:hidden/"
                          f"opacity:0) — nothing on a static slide may be invisible")
        for m in re.findall(r"var\((--[\w-]+)\)", style_text):
            if m not in allowed_vars:
                errors.append(f"E3 {p.name}: unknown var {m}")
        for rx, label in FORBIDDEN_STYLE:
            if rx.search(style_text):
                errors.append(f"E4 {p.name}: forbidden {label}")
        for rx, label in FORBIDDEN_TAGS:
            if rx.search(body):
                errors.append(f"E4 {p.name}: forbidden {label}")

        lay = re.search(r'data-layout="([\w-]+)"', body)
        ryt = re.search(r'data-rhythm="([\w-]+)"', body)
        lay_v = lay.group(1) if lay else None
        ryt_v = ryt.group(1) if ryt else None
        if lay_v not in layouts_registry:
            errors.append(f"E5 {p.name}: data-layout={lay_v!r} not in registry {sorted(layouts_registry)}")
        if ryt_v not in VALID_RHYTHMS:
            errors.append(f"E5 {p.name}: data-rhythm={ryt_v!r} invalid")
        layouts.append(lay_v or "?")
        if n in outline:
            want_lay, want_ryt = outline[n].get("layout"), outline[n].get("rhythm")
            if want_lay and lay_v != want_lay:
                errors.append(f"E5 {p.name}: layout {lay_v} != outline {want_lay}")
            if want_ryt and ryt_v != want_ryt:
                errors.append(f"E5 {p.name}: rhythm {ryt_v} != outline {want_ryt}")
            # E10 — scenario (fictional) data pages promise a visible 「示意」 label;
            # E9 above guarantees "in the text" means "actually visible"
            evs = outline[n].get("evidence") or []
            if (isinstance(evs, list)
                    and any(isinstance(ev, dict) and ev.get("scenario") is True for ev in evs)
                    and not any(m in visible.lower() if m.isascii() else m in visible
                                for m in scenario_markers)):
                errors.append(f"E10 {p.name}: scenario data page must render a visible "
                              f"scenario label {scenario_markers} "
                              f"(outline marks its evidence scenario:true)")

        for rx in PLACEHOLDER_RES:
            if rx.search(visible):
                errors.append(f"E6 {p.name}: placeholder residue ({rx.pattern})")
                break

        for m in re.findall(r"(?:margin|padding|gap)[^:;]*:\s*([\d]+)px", style_text):
            if int(m) % 8 != 0:
                warns.append(f"W1 {p.name}: {m}px off the 8px module")
        if ryt_v == "breathing":
            vlen = len(re.sub(r"\s+", "", visible))
            if vlen > 120:
                warns.append(f"W2 {p.name}: breathing page has {vlen} chars of text")

    if not single:
        # E5 — contiguous 1..N page numbers: shots/pptx/notes alignment maps
        # list position to page number, so holes would silently shift them all
        nums = [page_no(p) for p in pages]
        if nums != list(range(1, len(pages) + 1)):
            errors.append(f"E5 page numbers not contiguous 1..{len(pages)}: {nums}")
        # schema contract: >=8 pages need >=6 distinct layouts (small decks are
        # free to repeat — forcing variety on a 5-pager degrades, not improves)
        distinct = len(set(layouts))
        if len(pages) >= 8 and distinct < 6:
            errors.append(f"E7 layout diversity: {distinct} distinct < 6 required for {len(pages)} pages")
        run = max(len(list(g)) for _, g in itertools.groupby(layouts))
        if run >= 3:
            errors.append(f"E7 {run} consecutive pages share one layout (max 2)")
        if outline and set(nums) != set(outline):
            errors.append(f"E5 page numbers {sorted(set(nums))} != outline indexes {sorted(outline)}")

    for w in warns:
        print("WARN ", w)
    for e in errors:
        print("ERROR", e)

    # qa_report.json aggregation — the "structure" section; probe_overflow.py
    # appends its own section. Receipt rule: pages listed must equal pages seen.
    report_f = proj / "qa_report.json"
    report = {}
    if report_f.is_file():
        try:
            report = json.loads(report_f.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            report = {}
    report["structure"] = {
        "mode": "single" if single else "full",
        "pages": [page_no(p) for p in pages],
        "layouts": layouts,
        "errors": errors,
        "warnings": warns,
    }
    report_f.write_text(json.dumps(report, ensure_ascii=False, indent=1), encoding="utf-8")

    print(f"validate: {len(pages)} pages · layouts={layouts} · {len(errors)} errors · {len(warns)} warnings")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
