/**
 * builtin-skills-exclude.ts — single source of truth for what the builtin-skills
 * sentinel hash (and the packed zip) must exclude.
 *
 * ⚠️ Both scripts/pack-builtin-skills.ts (build-time zip + hash) and
 * scripts/fetch-builtin-skills.ts (writes the committed .builtin-version) walk
 * skills/builtin/ and must exclude EXACTLY the same paths, or the committed
 * sentinel and the build-time sentinel diverge → the desktop app reinstalls all
 * builtin skills on every launch. Keeping the rules here means the two walkers
 * can never drift by hand-copy.
 */

/** Local junk (Finder/Explorer artifacts, Python bytecode) — never content. */
export const JUNK = new Set([".DS_Store", "Thumbs.db", "__pycache__"])

/**
 * A directory whose contents are regenerated by a skill's regression chain
 * (e.g. skills/builtin/deckcraft/examples/ai-coding-pilot/export/). Matched on
 * the '/'-joined relative path from skills/builtin. Not committed (.gitignore),
 * so it must not enter the hash either — else a dev machine that ran the chain
 * produces a different sentinel than clean CI.
 */
export function isGeneratedDir(relPath: string): boolean {
  return /(^|\/)examples\/[^/]+\/export$/.test(relPath)
}
