#!/usr/bin/env bun
// Build-time generator: Traditional Chinese (zh-Hant) dictionary (ADR-058 D3).
//
// Source of truth is the hand-written `zhHans` dictionary. This script converts
// every value to Taiwan Traditional Chinese via opencc-js (`s2twp` = Simplified
// → Traditional w/ Taiwan phrases) and writes a static module. Nothing converts
// at runtime; the app just reads the generated dictionary like en / zh-Hans.
//
//   Regenerate:  bun run --bun scripts/gen-zh-hant.ts
//   Drift guard: check-docs.ts re-runs this and fails if the committed output
//                differs (i.e. someone edited zhHans without regenerating).
//
// opencc-js is a devDependency only — it never ships in the renderer bundle.

import * as OpenCC from "opencc-js"
import { zhHans } from "../packages/client/desktop/src/lib/i18n-translations"

const OUT = new URL("../packages/client/desktop/src/lib/i18n-zh-hant.generated.ts", import.meta.url)

// App-specific overrides applied AFTER opencc (highest priority). opencc `twp`
// already localizes the vast majority of UI terms (软件→軟體, 界面→介面,
// 默认→預設, 设置→設定, 任务栏→工作列, …), so this stays near-empty — add an
// entry only when opencc mistranslates a product-specific term. Order matters:
// longer keys first so they win over any substring.
const OVERRIDES: Record<string, string> = {
  // "示例简体": "示例繁體",
}

const convert = OpenCC.Converter({ from: "cn", to: "twp" })

function toHant(s: string): string {
  let out = convert(s)
  for (const [from, to] of Object.entries(OVERRIDES)) {
    out = out.split(from).join(to)
  }
  return out
}

// Preserve zhHans key order → stable, reviewable diffs.
function buildContent(): string {
  const body = Object.entries(zhHans)
    .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(toHant(v))},`)
    .join("\n")

  const header = `// AUTO-GENERATED by scripts/gen-zh-hant.ts — DO NOT EDIT BY HAND.
//
// Traditional Chinese (Taiwan) dictionary, converted from \`zhHans\` in
// i18n-translations.ts via opencc-js (s2twp). To change a string, edit the
// Simplified source and regenerate:  bun run --bun scripts/gen-zh-hant.ts
// (ADR-058 D3). check-docs.ts fails if this file drifts from a fresh run.

export const zhHant: Record<string, string> = {
`
  return header + body + "\n}\n"
}

// Run as a script: `--check` verifies the committed file matches a fresh build
// (drift guard for check-docs/CI); default writes the file.
if (import.meta.main) {
  const content = buildContent()
  const check = process.argv.includes("--check")
  if (check) {
    const current = (await Bun.file(OUT).exists()) ? await Bun.file(OUT).text() : ""
    // Compare line-ending-agnostically: on Windows CI (`core.autocrlf`) the
    // committed LF file is checked out as CRLF, and this generator's own source
    // (the header template literal) may likewise be CRLF — a raw byte compare
    // would then spuriously report drift on Windows only. Normalizing both sides
    // makes the guard about content, not EOL. (.gitattributes also pins LF.)
    const normalize = (s: string) => s.replace(/\r\n/g, "\n")
    if (normalize(current) !== normalize(content)) {
      console.error(
        "gen-zh-hant --check: i18n-zh-hant.generated.ts is stale. " +
          "Run `bun run --bun scripts/gen-zh-hant.ts` and commit the result.",
      )
      process.exit(1)
    }
    console.log("gen-zh-hant --check: up to date.")
  } else {
    await Bun.write(OUT, content)
    console.log(`gen-zh-hant: wrote ${Object.keys(zhHans).length} keys → ${OUT.pathname}`)
  }
}
