// W1 spike gate (ADR-027): replay a REAL claude turn captured through the ACP
// sidecar's shaping pipeline (fixtures/acp-claude-turn.json, generated by
// packages/agent/acp-client/scripts/spike-claude.ts) and assert the ADR-029
// turn renderer splits process/answer correctly.
//
// The replay reducer below mirrors handleSSEEvent (use-session-messages.ts):
// - message.part.updated upserts the part, creating the message if absent
// - message.part.delta appends only to an existing part (dropped otherwise)
// - message.updated merges info into an existing message

import { describe, it, expect } from "vitest"
import { buildTurnModel } from "@/components/chat/assistant-turn"
import { groupIntoTurns } from "@/components/chat/message-list"
import type { MessagePart, SendMessageResponse, ToolPart } from "@agent/api-client"
import rawFixture from "../../fixtures/acp-claude-turn.json"

interface ShapedEvent {
  type: string
  properties: Record<string, any>
}

const fixture = rawFixture as ShapedEvent[]

function replay(events: ShapedEvent[]): SendMessageResponse[] {
  const messages: SendMessageResponse[] = []
  const byId = (id: string) => messages.find((m) => m.info.id === id)
  for (const event of events) {
    switch (event.type) {
      case "message.part.updated": {
        const part = event.properties.part as MessagePart & { id: string; messageID: string }
        let msg = byId(part.messageID)
        if (!msg) {
          msg = {
            info: { id: part.messageID, sessionID: part.sessionID, role: "assistant", time: { created: 1 } },
            parts: [],
          }
          messages.push(msg)
        }
        const idx = msg.parts.findIndex((p) => "id" in p && (p as any).id === part.id)
        if (idx >= 0) msg.parts[idx] = part
        else msg.parts.push(part)
        break
      }
      case "message.part.delta": {
        const { messageID, partID, field, delta } = event.properties
        const msg = byId(messageID)
        const part = msg?.parts.find((p) => "id" in p && (p as any).id === partID) as any
        if (part) part[field] = (part[field] || "") + delta
        break
      }
      case "message.updated": {
        const info = event.properties.info
        const msg = byId(info.id)
        if (msg) msg.info = { ...msg.info, ...info }
        break
      }
    }
  }
  return messages
}

const user = (id: string, text: string): SendMessageResponse => ({
  info: { id, sessionID: "ses", role: "user", time: { created: 0 } },
  parts: [{ type: "text", id: `${id}-p`, sessionID: "ses", messageID: id, text } as MessagePart],
})

describe("ACP turn shaping → buildTurnModel (real claude fixture)", () => {
  it("emits every delta after a part.updated created its part", () => {
    const seen = new Set<string>()
    for (const event of fixture) {
      if (event.type === "message.part.updated") seen.add(event.properties.part.id)
      if (event.type === "message.part.delta") {
        expect(seen.has(event.properties.partID)).toBe(true)
      }
    }
  })

  it("splits the turn into process (tool steps) and a text-only answer", () => {
    const assistant = replay(fixture)
    expect(assistant.length).toBeGreaterThanOrEqual(2)

    const groups = groupIntoTurns([user("u1", "list the files"), ...assistant])
    expect(groups.map((g) => g.kind)).toEqual(["user", "assistant"])
    const turnMessages = groups[1].kind === "assistant" ? groups[1].messages : []
    expect(turnMessages).toHaveLength(assistant.length)

    const model = buildTurnModel(turnMessages, false)

    // The final answer surfaces as output (not swallowed into the flow).
    expect(model.answer.length).toBeGreaterThan(0)
    expect(model.answer.every((p) => p.type === "text")).toBe(true)
    const answerText = model.answer.map((p) => (p as { text?: string }).text ?? "").join("")
    expect(answerText.length).toBeGreaterThan(0)

    // Tool steps land in process, completed, no duplicates per callID.
    const toolParts = model.process.filter((p): p is ToolPart => p.type === "tool")
    expect(toolParts.length).toBeGreaterThan(0)
    const callIDs = toolParts.map((p) => p.callID)
    expect(new Set(callIDs).size).toBe(callIDs.length)
    expect(toolParts.every((p) => p.state.status === "completed")).toBe(true)
    expect(model.hasError).toBe(false)

    // Answer parts must not appear in process and vice versa.
    expect(model.process.some((p) => model.answer.includes(p))).toBe(false)
  })

  it("ends the turn with a terminal finish (spinner stops)", () => {
    const assistant = replay(fixture)
    const lastInfo = assistant[assistant.length - 1].info
    // message-list.tsx isTerminal: finish set && !== "tool-calls"
    expect(lastInfo.finish).toBeTruthy()
    expect(lastInfo.finish).not.toBe("tool-calls")
    expect(lastInfo.time.completed).toBeGreaterThan(0)
    // Intermediate messages are sealed as tool steps.
    for (const msg of assistant.slice(0, -1)) {
      expect(msg.info.finish).toBe("tool-calls")
    }
  })

  it("keeps the answer empty while a tool step is still streaming", () => {
    // Truncate the stream right before the answer message's first text part.
    const cut = fixture.findIndex(
      (e) => e.type === "message.part.updated" && e.properties.part.type === "text",
    )
    expect(cut).toBeGreaterThan(0)
    const assistant = replay(fixture.slice(0, cut))
    expect(assistant.length).toBeGreaterThan(0)

    const model = buildTurnModel(assistant, true)
    // Last message still has a tool part → not the answer step → no flicker.
    expect(model.answer).toHaveLength(0)
    expect(model.process.length).toBeGreaterThan(0)
  })
})
